---
title: "Case Study 11"
author: Micaela Lipman
last edited: November 18, 2021
output: github_document
editor_options: 
  chunk_output_type: console
---

load libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F, cache = T)
library(tidyverse)
library(spData)
library(sf)
library(sp)
library(mapview) # new package that makes easy leaflet maps
library(foreach)
library(doParallel)
library(raster)
library(dplyr)
library(tidycensus)
# census API key can be obtained from: http://api.census.gov/data/key_signup.html

census_api_key("74a0ccb1101358271c49d0f3c2cfffc9fb5ac3ae", install = TRUE, overwrite=TRUE)
readRenviron("~/.Renviron")
```


## Load data 
```{r}
racevars <- c(White = "P005003", 
              Black = "P005004", 
              Asian = "P005006", 
              Hispanic = "P004003")
options(tigris_use_cache = TRUE)
erie <- get_decennial(geography = "block", variables = racevars, 
                      state = "NY", county = "Erie County", geometry = TRUE,
                      summary_var = "P001001", cache_table=T) 
```

## Crop the county-level data

```{r}
erie_crop <- st_crop(erie,xmin=-78.9,xmax=-78.85,ymin=42.888,ymax=42.92)

```

## Parallel computing

```{r}
racial_group <- foreach(r=unique(erie_crop$variable),.combine=rbind) %dopar%{
    filter(erie_crop,variable==r) %>%
    st_sample(size =.$value) %>%
    st_as_sf() %>%
    mutate(variable=r)
}

```

## Visualize

```{r}
mapview(racial_group, zcol="variable", cex=0.01, alpha = 0)
```
 